using System.ComponentModel.DataAnnotations;

namespace EducationCourseManagement.DTOs
{
    public class ScheduleDTO
    {
        public int ScheduleId { get; set; }

        [Required(ErrorMessage = "CourseId is required.")]
        [Range(1, int.MaxValue, ErrorMessage = "Invalid CourseId.")]
        public int CourseId { get; set; }

        [Required(ErrorMessage = "InstructorId is required.")]
        [Range(1, int.MaxValue, ErrorMessage = "Invalid InstructorId.")]
        public int InstructorId { get; set; }

        [Required(ErrorMessage = "RoomId is required.")]
        [Range(1, int.MaxValue, ErrorMessage = "Invalid RoomId.")]
        public int RoomId { get; set; }

        [Required(ErrorMessage = "Date is required.")]
        public DateTime Date { get; set; }

        [Required(ErrorMessage = "TimeSlot is required.")]
        [StringLength(50, ErrorMessage = "TimeSlot cannot exceed 50 characters.")]
        public string TimeSlot { get; set; }

        public bool IsAutoGenerated { get; set; } = false;

        [StringLength(255, ErrorMessage = "GeneratedBy cannot exceed 255 characters.")]
        public string GeneratedBy { get; set; }
    }
}